/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-kiosk.h
 #	source generated by 4D Plugin Wizard
 #	Project : kiosk
 #	author : miyako
 #	2022/07/06
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_KIOSK_H
#define PLUGIN_KIOSK_H

#include "4DPluginAPI.h"

#if VERSIONWIN
#include "shlwapi.h"
#pragma comment(lib, "shlwapi.lib")
#define HKCU HKEY_CURRENT_USER
LPCWSTR KEY_DisableTaskMgr = L"Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System";
LPCWSTR VAL_DisableTaskMgr = L"DisableTaskMgr";
#else
#import <AppKit/AppKit.h>
#endif

typedef enum {
    kiosk_mode_off   = 0,
    kiosk_mode_on    = 1
} kiosk_mode_t;

#pragma mark -

void KIOSK_SET_MODE(PA_PluginParameters params);
void KIOSK_Get_mode(PA_PluginParameters params);

#endif /* PLUGIN_KIOSK_H */
